<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'wt_galerie.antispam' shared service.

include_once $this->targetDirs[3].'/src/WT/GalerieBundle/Antispam/WTAntispam.php';

return $this->services['wt_galerie.antispam'] = new \WT\GalerieBundle\Antispam\WTAntispam(${($_ = isset($this->services['swiftmailer.mailer.default']) ? $this->services['swiftmailer.mailer.default'] : $this->load(__DIR__.'/getSwiftmailer_Mailer_DefaultService.php')) && false ?: '_'}, 'fr', 50);
