# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        WT\UserBundle\Entity\User: sha512
        #Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]


    # # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    # providers:
    #     in_memory:
    #         memory: ~
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
            #entity:
            #    class:    WT\UserBundle\Entity\User
            #    property: username
        
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }



    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            ##anonymous: ~
            # activate different ways to authenticate
            pattern:    ^/
            anonymous:  true
            provider:   fos_userbundle
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                use_referer: true
                #csrf_provider: security.csrf.token_manager
                default_target_path: /galerie
                #failure_path: login_failure_route_name
            logout:
                path:       fos_user_security_logout
                target:     fos_user_security_login
            remember_me: 
                secret:     %secret% # %secret% est un paramètre de parameter



            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/galerie/admin/, role: ROLE_ADMIN }