<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'doctrine.fixtures_load_command' shared service.

include_once $this->targetDirs[3].'/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Loader.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Bridge/Doctrine/DataFixtures/ContainerAwareLoader.php';
include_once $this->targetDirs[3].'/vendor/doctrine/doctrine-fixtures-bundle/Loader/SymfonyFixturesLoader.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Command/ContainerAwareCommand.php';
include_once $this->targetDirs[3].'/vendor/doctrine/doctrine-bundle/Command/DoctrineCommand.php';
include_once $this->targetDirs[3].'/vendor/doctrine/doctrine-fixtures-bundle/Command/LoadDataFixturesDoctrineCommand.php';
include_once $this->targetDirs[3].'/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/FixtureInterface.php';
include_once $this->targetDirs[3].'/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/SharedFixtureInterface.php';
include_once $this->targetDirs[3].'/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/AbstractFixture.php';
include_once $this->targetDirs[3].'/vendor/doctrine/doctrine-fixtures-bundle/ORMFixtureInterface.php';
include_once $this->targetDirs[3].'/vendor/doctrine/doctrine-fixtures-bundle/Fixture.php';
include_once $this->targetDirs[3].'/src/WT/UserBundle/DataFixtures/ORM/LoadUser.php';
include_once $this->targetDirs[3].'/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/DependentFixtureInterface.php';
include_once $this->targetDirs[3].'/src/WT/GalerieBundle/DataFixtures/ORM/LoadGalerie.php';
include_once $this->targetDirs[3].'/src/WT/GalerieBundle/DataFixtures/ORM/LoadGalerieItem.php';

$a = new \Doctrine\Bundle\FixturesBundle\Loader\SymfonyFixturesLoader($this);
$a->addFixtures(array(0 => ${($_ = isset($this->services['wt_user.fixture']) ? $this->services['wt_user.fixture'] : $this->services['wt_user.fixture'] = new \WT\UserBundle\DataFixtures\ORM\LoadUser()) && false ?: '_'}, 1 => ${($_ = isset($this->services['wt_galerie.fixture']) ? $this->services['wt_galerie.fixture'] : $this->services['wt_galerie.fixture'] = new \WT\GalerieBundle\DataFixtures\ORM\LoadGalerie()) && false ?: '_'}, 2 => ${($_ = isset($this->services['wt_galerieItem.fixture']) ? $this->services['wt_galerieItem.fixture'] : $this->services['wt_galerieItem.fixture'] = new \WT\GalerieBundle\DataFixtures\ORM\LoadGalerieItem()) && false ?: '_'}));

$this->services['doctrine.fixtures_load_command'] = $instance = new \Doctrine\Bundle\FixturesBundle\Command\LoadDataFixturesDoctrineCommand($a);

$instance->setName('doctrine:fixtures:load');

return $instance;
