<?php

namespace WT\GalerieBundle\Repository;

/**
 * GalerieElementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GalerieElementRepository extends \Doctrine\ORM\EntityRepository
{
}
