<?php

namespace WT\GalerieBundle\Repository;

/**
 * GalerieItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GalerieItemRepository extends \Doctrine\ORM\EntityRepository
{
}
