<?php

namespace WT\GalerieBundle\Repository;

/**
 * GalerieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GalerieRepository extends \Doctrine\ORM\EntityRepository
{
}
