<?php

namespace WT\GalerieBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * GalerieItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GalerieItemRepository extends \Doctrine\ORM\EntityRepository
{
	public function getLikeQueryBuilder($pattern)
	{
		return $this->createQueryBuilder('g')
			->where('g.ispublished LIKE :pattern')
			->setParameter('pattern', $pattern)

    ;

  }
}
