<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQpbqxcv\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQpbqxcv/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerQpbqxcv.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerQpbqxcv\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerQpbqxcv\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Qpbqxcv',
    'container.build_id' => 'd21290a3',
    'container.build_time' => 1524061083,
));
